### ISSUE TITLE
Idea: Standardized way to override HTTP methods in forms

### ISSUE THREAD

**Issue by chkal** [eclipse-ee4j/mvc-api#39]
<a href="https://github.com/erdlet"><img src="https://avatars0.githubusercontent.com/u/43722450?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erdlet](https://github.com/erdlet)**
_Monday Sep 02, 2019 at 15:14 GMT_
_Originally opened as https://github.com/mvc-spec/mvc-spec/issues/219_

----

Hi all,

a few months ago, a feature to was added to Krazo which enables developers to override the HTTP method used in HTML forms by setting a hidden field that is evaluated while the request is processed. This way, developers can implement controllers which are using the full power of HTTP verbs what results in clearer and more understandable APIs.

Therefore I wanted to ask what you think about standardizing this functionality in the MVC API to ensure every person using an MVC implementation can profit from it. Also, this is something which nearly all MVC frameworks I know support (e.g. Spring MVC, Rails, Grails, Django) very successfully.

**Comment by chkal** [comment]
<a href="https://github.com/chkal"><img src="https://avatars2.githubusercontent.com/u/159245?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chkal](https://github.com/chkal)**
_Friday Sep 06, 2019 at 12:37 GMT_

----

Thanks for creating this issue.

If this is a feature provided by most of the other MVC frameworks, we should definitely support it. And it should be more or less easy to do.

I'll assign this issue to "Future" so we can consider it for MVC 1.1.

**Comment by ivargrimstad** [comment]
Closed by https://github.com/eclipse-ee4j/mvc-api/pull/72
