### ISSUE TITLE
Compatibility certification request for Eclipse Krazo 1.1.0

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/mvc-api#45]
- [x] Organization Name ("Organization") and, if applicable, URL:
  [Eclipse Foundation](https://www.eclipse.org/)
- [x] Product Name, Version and download URL (if applicable):
  [Eclipse Krazo 1.1.0](https://eclipse-ee4j.github.io/krazo/downloads/1.1.0.html)
- [x] Specification Name, Version and download URL:
   [Jakarta MVC 1.1](https://jakarta.ee/specifications/mvc/1.1)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:
  [Jakarta MVC TCK 1.1.0](https://download.eclipse.org/jakartaee/mvc/1.1/jakarta-mvc-tck-1.1.0.zip)
  SHA-256: `971bb7886f9126b2adace32e30d9f71d71a79930eacd2bf6c68d010b803de6b1`
- [x] Public URL of TCK Results Summary:
  [TCK Results](https://eclipse-ee4j.github.io/krazo/certifications/jakarta-mvc/1.1/TCK-results.html)
- [x] Any Additional Specification Certification Requirements:
  None
- [x] Java runtime used to run the implementation:
  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
  OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:
  5.4.0-48-generic #52-Ubuntu
  wildfly-18.0.1.Final
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by chkal** [comment]
:+1: :tada:

**Comment by Pandrex247** [comment]
There's a slight typo in the public TCK results URL.

The link points to https://eclipse-ee4j.github.io/krazo/certifications/jakarta-mvc/1.1/TCK-Results.html but when clicked gives a 404 due to the actual page not having a capital **R**: https://eclipse-ee4j.github.io/krazo/certifications/jakarta-mvc/1.1/TCK-results.html

**Comment by ivargrimstad** [comment]
Thanks @Pandrex247 ! Just fixed it :)
