### ISSUE TITLE
Compatibility Certification Request for Eclipse Krazo 2.0.0

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/mvc-api#53]
- [x] Organization Name ("Organization") and, if applicable, URL:
  [Eclipse Foundation](https://eclipse.org)
- [x] Product Name, Version and download URL (if applicable):
  [Eclipse Krazo 2.0.0](https://eclipse-ee4j.github.io/krazo/downloads/2.0.0.html)
- [x] Specification Name, Version and download URL:
   [Jakarta MVC 2.0](https://jakarta.ee/specifications/mvc/2.0)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:
  [Jakarta MVC TCK 2.0.0](https://download.eclipse.org/jakartaee/mvc/2.0/jakarta-mvc-tck-2.0.0.zip)
  [Jakarta MVC TCK 2.0.0 (staged)](https://download.eclipse.org/ee4j/mvc/staged/2.0/jakarta-mvc-tck-2.0.0.zip)
  SHA-256: `27a09b18169e46571898375d2eb1d05000301828c5d16dfc5d56e882690d55ed`
- [x] Public URL of TCK Results Summary:
  https://eclipse-ee4j.github.io/krazo/certifications/jakarta-mvc/2.0/TCK-Results.html
- [x] Any Additional Specification Certification Requirements:
  None
- [x] Java runtime used to run the implementation:
  - Testrun 1: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
  - Testrun 2: OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:
  - 5.8.0-29-generic #31-Ubuntu x86_64 GNU/Linux
  - Testrun 1: Eclipse GlassFish 6.0.0-RC2
  - Testrun 2: WildFly 22.0.0.Alpha1
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by chkal** [comment]
LGTM! :+1:
