### ISSUE TITLE
Access javax.ws.rs.core.UriInfo.getAbsolutePath() in views

### ISSUE THREAD

**Issue by alekic** [eclipse-ee4j/mvc-api#56]
Is it possible to get the value of `javax.ws.rs.core.UriInfo.getAbsolutePath()` of the current request in a view (e.g. a JSP page)? A typical use case would be to style a navigation link differently if the request URI matches the link URI.

It would be nice to be able to do something like this:
```html
<nav>
    <a class="${mvc.requestUri eq mvc.uri('MyController#home') ? 'active' : ''}" href="${mvc.uri('MyController#home')}">Home</a>
</nav>

**Comment by chkal** [comment]
I don't think that there is a portal way of doing this at the moment.

However, if you are using Eclipse Krazo, you should be able to do something like this:

```java
@Named
@RequestScoped
public class MvcHelper {

    @Inject
    @org.eclipse.krazo.cdi.Internal
    private UriInfo uriInfo;

    public String getAbsolutePath() {
        return uriInfo.getAbsolutePath().toASCIIString();
    }

}
```

And then:

```html
<nav>
    <a class="${mvcHelper.absolutePath eq mvc.uri('MyController#home') ? 'active' : ''}" href="${mvc.uri('MyController#home')}">Home</a>
</nav>
```

**Comment by alekic** [comment]
@chkal Thank you for your quick reply. This solution works for me. I'm gonna close this issue.

**Comment by chkal** [comment]
Great! Happy to hear the workaround works for you. But please note that `org.eclipse.krazo.cdi.Internal` is actually a Krazo internal API. So it will definitely not work with other implementations (although Krazo is currently the only one) and that the API may change in the future (although I doubt that).
