### ISSUE TITLE
Compatibility Certification Request for Eclipse GlassFish 6.2.0

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/mvc-api#68]
- [x] Organization Name ("Organization") and, if applicable, URL:
  [Eclipse Foundation](https://eclipse.org)
- [x] Product Name, Version and download URL (if applicable):
  [Eclipse GlassFish 6.2.0](https://download.eclipse.org/ee4j/glassfish/glassfish-6.2.0.zip)
- [x] Specification Name, Version and download URL:
   [Jakarta MVC 2.0](https://jakarta.ee/specifications/mvc/2.0)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:
  [Jakarta MVC TCK 2.0.0](https://download.eclipse.org/jakartaee/mvc/2.0/jakarta-mvc-tck-2.0.0.zip)
  SHA-256: `27a09b18169e46571898375d2eb1d05000301828c5d16dfc5d56e882690d55ed`
- [x] Public URL of TCK Results Summary:
  https://glassfish.org/certifications/jakarta-mvc/2.0/TCK-Results-6.2.0
- [x] Any Additional Specification Certification Requirements:
  None
- [x] Java runtime used to run the implementation:
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```
- [x] Summary of the information for the certification environment, operating system, cloud, ...:
  `Linux basic-7b0jn 5.12.7-300.fc34.x86_64 #1 SMP Wed May 26 12:58:58 UTC 2021 x86_64 GNU/Linux`
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by chkal** [comment]
LGTM! Thanks! :+1:
